BOT_TOKEN: ""
DATABASE_URL: ""
OPENAI_API_TOKEN: ""
OPENAI_MODEL: ""
ADMIN_USER_IDS: []

deafentracker:
  enabled: false
  muted_is_deafened: false
  users: []

lavalink:
  nodes:
    - name: "localhost"
      url: "localhost:2333"
      auth: "youshallnotpass"
      secure: false
