BOT_TOKEN: ""
DATABASE_URL: ""
ADMIN_USER_IDS: []

openai:
  OPENAI_API_TOKEN: ""
  OPENAI_MODEL: ""

tiktok:
  TIKTOK_SESSION_ID: ""

spotify:
  SPOTIFY_CLIENT_ID: ""
  SPOTIFY_CLIENT_SECRET: ""

imgur:
  IMGUR_CLIENT_ID: ""

deafentracker:
  enabled: false
  muted_is_deafened: false
  users: []

riot:
  RIOT_API_KEY: ""
  pollIntervalSeconds: 60
  players: []

lavalink:
  nodes:
    - name: "localhost"
      url: "localhost:2333"
      auth: "youshallnotpass"
      secure: false
