BOT_TOKEN: ""
DATABASE_URL: ""
OPENAI_API_TOKEN: ""
OPENAI_MODEL: ""
TIKTOK_SESSION_ID: ""
SPOTIFY_CLIENT_ID: ""
SPOTIFY_CLIENT_SECRET: ""
RIOT_API_KEY: ""
ADMIN_USER_IDS: []

deafentracker:
  enabled: false
  muted_is_deafened: false
  users: []

riot:
  pollIntervalSeconds: 60
  players: []

lavalink:
  nodes:
    - name: "localhost"
      url: "localhost:2333"
      auth: "youshallnotpass"
      secure: false
